### ISSUE TITLE
Improve multiline string diff

### ISSUE THREAD

**Issue by mroderick** [sinonjs/referee#20]
We should replace the internal helper `multiLineStringDiff` with [`diff`][1] and [`color`](https://github.com/Qix-/color#readme). Both modules are well established, work in our target runtimes and are easy to use.

As can be seen in the code coverage report, the existing code is not covered by tests

![2018-03-08 at 08 04](https://user-images.githubusercontent.com/20321/37137723-5e76ea1e-22a7-11e8-9963-4fee8383193e.png)

#### Background 

https://github.com/sinonjs/referee/blob/263895719b23b5d4a6eddb27664df686099f830e/lib/referee.js#L250-L271

#### Acceptance criteria

* works in node
* works in browsers
* has tests :)

[1]: https://www.npmjs.com/package/diff

**Comment by mantoni** [comment]
I started looking into diff output, mainly because referee is not showing a very helpful error message when `assert.equals` fails on comparing two objects.

It seems like most test framewoks have a useful implementation for this based on `expected` and `actual` properties exposed on thrown errors. This is the way the Node `assert` module creates errors and maybe referee should do the same.

It makes sense to leave this to the test runner because there users can turn the behavior on or off and it might depend on the reporter in use to which level of detail and in which format the diff can be rendered (think console vs html vs json).

This would make the `multilineStringDiff` implementation entirely superfluous and also give us object diffs in a supporting framework.

I ran some quick checks with Mocha and it's relatively easy to make the change.
@mroderick What do you think?

**Comment by mroderick** [comment]
I like the idea of leaving it up to the test runner, as people will like things to be as homogenous in their chosen environments.

**Comment by mroderick** [comment]
With #35 merged and published, I think this is significantly improved. I think we can close this
